name: Build
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install latest npm
        run: npm install -g npm
      - name: Install dependencies
        uses: bahmutov/npm-install@cb39a46f27f14697fec763d60fb23ad347e2befa # tag=v1
        with:
          useRollingCache: true
      - name: Run unit & E2E tests
        run: npm test
